Feature/admin 142 servant validation
firstlovecenter/fl-admin-portal pull request #171
Opened 2022-06-08 22:44 UTC by dabick14

2022-06-09 13:11 UTC, jaedag requested changes

2022-06-09 13:14 UTC, dabick14 commented on api/src/resolvers/resolvers.js
> +    return
It's supposed to make sure that the subsequent parts of the function don't run.

2022-06-09 13:20 UTC, dabick14 commented on api/src/resolvers/resolver-utils.js
> +export const splitAuthId = (authID) => {
Ok

2022-06-09 21:14 UTC, dabick14 commented on web-react/src/pages/dashboards/LogInQueries.js
> +        vacationStatus
I'm not sure why this seems to have changed. Didn't work in this file

2022-06-10 18:33 UTC, dabick14 commented on web-react/src/pages/dashboards/LogMeIn.jsx
> +    const member = response?.data?.members?.length
I've pulled from the original deploy. Hope it solves the issue

2022-06-24 10:56 UTC, jaedag commented
Hi. Just reminding that we are waiting for your changes to merge this PR @dabick14

2022-06-24 10:57 UTC, jaedag commented
By this point you should probably close this PR and redo your changes in a new branch off of deploy

2022-06-24 19:09 UTC, jaedag commented
What about this one?

2022-06-24 19:17 UTC, dabick14 commented
Made the changes. Will pull from deploy and submit another request

2022-06-24 19:28 UTC, closed without merging