fix: admin-197 fixed bug where updating name of constituency not working
firstlovecenter/fl-admin-portal pull request #193
Opened 2022-07-01 16:37 UTC by dabick14

2022-07-01 16:40 UTC, jaedag requested changes
Did you check that the correct history was being written as well?

2022-07-01 17:00 UTC, jaedag commented
Please make the change it's very small.

2022-07-02 20:08 UTC, dabick14 commented on web-react/src/pages/directory/update/UpdateConstituency.jsx
> +    council: constituency?.council?.id,
Removing it now. Thank you

2022-07-02 20:52 UTC, jaedag approved these changes

2022-07-02 20:53 UTC, jaedag approved these changes

2022-07-02 20:53 UTC, merged