Feature implement oversight page fix
firstlovecenter/fl-admin-portal pull request #210
Opened 2022-07-15 09:53 UTC by fldata22

2022-07-20 20:00 UTC, ahadziii commented
Says there are conflicts

2022-07-20 21:22 UTC, jaedag commented
@fldata22 conflicts?

2022-07-20 22:03 UTC, fldata22 commented
> @fldata22 conflicts?

all sorted now

2022-07-21 08:51 UTC, jaedag commented on api/src/resolvers/aggregates/component-service-cypher.ts
> +  MATCH (church)-[:HAS_HISTORY]->(:ServiceLog)-[:HAS_COMPONENT*1..5]->(componentServices:ServiceLog)
Why HAS_COMPONENT 1..5?

2022-07-28 08:44 UTC, jaedag commented on api/src/resolvers/aggregates/component-service-cypher.ts
> +  MATCH (church)-[:HAS_HISTORY]->(:ServiceLog)-[:HAS_COMPONENT*1..5]->(componentServices:ServiceLog)
??

2022-07-28 09:01 UTC, jaedag requested changes

2022-07-28 09:01 UTC, jaedag commented on web-react-ts/src/pages/directory/quick-facts/this-month/GatheringServiceAvgWeekdayQuickFacts.jsx
>        leadersName: `${gatheringServiceAttendance?.leader?.firstName} ${gatheringServiceAttendance?.leader?.lastName}`,
Why a jsx file here?

2022-07-28 09:01 UTC, jaedag commented on web-react-ts/src/pages/directory/reusable-forms/GatheringServiceForm.jsx
> +import { useMutation, useQuery } from '@apollo/client'
Another jsx file

2022-07-28 12:42 UTC, jaedag requested changes

2022-07-28 12:42 UTC, jaedag commented on web-react-ts/src/pages/directory/grids/OversightMembers.tsx
> +    console.log(data),
Why a console log?

2022-07-28 13:11 UTC, jaedag requested changes

2022-07-28 13:11 UTC, jaedag commented on web-react-ts/src/pages/directory/grids/OversightMembers.tsx
> +// import TabletDesktopView from 'components/responsive-design/TabletDesktopView'
What's this comment about?

2022-07-28 13:15 UTC, jaedag approved these changes
This last commit message is not a good one. I'm letting it slide because you have worn me out with this PR

2022-07-28 13:17 UTC, merged