feat: implement equipment deadline on the equipment main page
firstlovecenter/fl-admin-portal pull request #277
Opened 2022-09-08 08:29 UTC by ahadziii

## Description

Added equipment deadline to the so to the main equipment pages of the various church levels so a user can know when the equipment season is ending"

## Related Issue

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

## Screenshots/Videos (if appropriate):

![localhost_3000_campaigns_council_equipment(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/36607706/189074429-1ab2f35d-b849-4077-aa6a-17a0337c32f5.png)

2022-09-08 08:45 UTC, dabick14 approved these changes

2022-09-08 08:48 UTC, jaedag commented
You should centre this red one.

2022-09-08 08:55 UTC, jaedag requested changes
Please centre the equipment date thing

2022-09-08 12:43 UTC, ahadziii commented
> Please centre the equipment date thing

Alright I will when I get home

2022-09-09 05:56 UTC, dabick14 approved these changes

2022-09-09 08:34 UTC, jaedag approved these changes

2022-09-09 08:35 UTC, merged