admin-422-TASK/write-cypher-script-to-create-test-environment-members-and churches
firstlovecenter/fl-admin-portal pull request #339
Opened 2022-11-10 17:09 UTC by dabick14

…nv script

## Description
This PR adds to the setup development cypher script and adds all the list of testers and developers as members, and leaves only one string of churches for campus, town and anagkazo.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
This has been tested on my local database.

## Screenshots/Videos (if appropriate):

<img width="885" alt="image" src="https://user-images.githubusercontent.com/36535410/201160567-aae7ac3a-34d9-415a-9ef8-86ffda3f31fb.png">
<img width="893" alt="image" src="https://user-images.githubusercontent.com/36535410/201160699-9d9662b2-5359-41a8-9a9d-d608811103d6.png">
<img width="885" alt="image" src="https://user-images.githubusercontent.com/36535410/201160758-2609d95c-8ae6-4b0f-9746-9168e38037f8.png">
<img width="883" alt="image" src="https://user-images.githubusercontent.com/36535410/201160945-40ef5fd8-10d5-45f5-8fc0-d55df97ccaf5.png">

2022-11-12 20:24 UTC, jaedag commented
Please request a review so that I get notifications instead of waiting for me to stumble across PRs

2022-11-12 20:27 UTC, jaedag requested changes

2022-11-12 20:27 UTC, jaedag commented on api/beforeSetupDevInstance.cypher
> +match (n:Member) where n.email in ['jaedagy@gmail.com', 'dabick14@gmail.com', 'ahadzi.airdem@gmail.com', 'asiaknathan@gmail.com', 'pri.davidakumah@gmail.com', 'enlogeesa@gmail.com', 'cranksonv@yahoo.
You forgot about martha

2022-11-12 22:33 UTC, dabick14 commented
Thanks. Will add herSent from my iPhoneOn 12 Nov 2022, at 8:27 PM, John-Dag Addy ***@***.***> wrote:﻿
@jaedag requested changes on this pull request.



In api/beforeSetupDevInstance.cypher:
> @@ -37,13 +37,49 @@ and not exists {
 }
 detach delete n;
 
-match (n:Member) where n.email in ***@***.***', ***@***.***', ***@***.***', ***@***.***']
+match (n:Member) where n.email in ***@***.***', ***@***.***', ***@***.***', ***@***.***', ***@***.***', ***@***.***', ***@***.******@***.***']

You forgot about martha

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-11-16 18:43 UTC, jaedag approved these changes

2022-11-16 18:43 UTC, merged